### ISSUE TITLE
[Question] Private messages

### ISSUE THREAD

**Issue by zalmoxisus** [SocketCluster/socketcluster-client#39]
Is there a way to emit a message from one socket to another one (knowing the socket.id) instead of creating a channel, subscribing to it and adding a middleware to prevent watching it by other users (which is somehow cumbersome)?

**Comment by jondubois** [comment]
Yes but you should keep in mind that a user could have multiple sockets open (on different browser tabs for example).

There are multiple ways to do what you want:

1. If you only intend to ever have 1 worker process, then on the client you can simply emit the message to the server, then you can handle that event from inside your worker, then get a reference to the target client socket using the ```scServer.clients``` property here: http://socketcluster.io/#!/docs/api-scserver and then emit the message to that socket directly. Note that this approach is not scalable - As soon as you add a second worker, half of the sockets will be hosted by a different worker than the one which is handling the message so it won't work. This approach is not recommended.

2. You can setup channels on the backend only using the ```worker.exchange``` object here: http://socketcluster.io/#!/docs/api-scworker. With this approach; whenever a new socket becomes connected, you can create a new channel from the server which is based on that socket's ID and subscribe to it (E.g. ```worker.exchange.subscribe('someSocketId123').watch(handlerFunction) ```) - The handlerFunction can then just capture all messages published to that channel and forward them to the appropriate client socket using ```socket.emit(...)```. Your server logic will be responsible for listening to events from clients using ```socket.on(eventName, handler)``` and relaying them to the appropriate backend channel using ```worker.exchange.publish('someSocketId123', message)```. You may want to set the ```allowClientPublish``` config of SC to ```false``` (see http://socketcluster.io/#!/docs/api-socketcluster) so that only the server can publish to channels. The idea of this approach would be to setup all channels on the backend only - That way clients only communicate to the server using ```socket.emit(...)``` and by listening to events using ```socket.on(...)```. Unlike the first approach, this one can scale quite well, but it means you have to manage channels on the backend (you have to remember to unsubscribe and destroy() the channel when the socket disconnects for example).

I think handling the channels on the frontend is generally a better/simpler approach overall but I understand that every case is different.

**Comment by zalmoxisus** [comment]
Thanks a lot for such a detailed explanation!

The first approach is exactly what I was searching for, but I see it is not scalable unless we find a way to notify all workers, and the one who handle such client id will emit the message (which I think is a worth direction to explore).

What bothers me in the second approach is the performance. Having thousands of clients means handling thousands of channels (additionally to the regular ones) just in case some users may receive some messages once in a while. Maybe I am mistaken and pub/sub is fast enough to ignore it?

**Comment by jondubois** [comment]
Channels in SC are pretty efficient, you can have many thousands of channels. The main problem would be if they all tried to subscribe at the same time (which could happen after a crash). But you can tweak the reconnect options to add randomness to the reconnect delay.

**Comment by zalmoxisus** [comment]
Thanks a bunch! It's awesome to have such a complex functionality done in just [few lines of code](https://github.com/zalmoxisus/remote-redux-devtools/blob/master/bin/worker.js). SocketCluster is a brilliant and handy piece of software!

In case someone will follow this instruction, we have also not to forget to set [`socketChannelLimit`](http://socketcluster.io/#!/docs/api-socketcluster) to a higher value, as we will have maximum `1000` users by default. Maybe is there a way to set it to unlimited?

**Comment by jondubois** [comment]
@zalmoxisus Note that there was an issue with the socketChannelLimit option in SC v4 basically the limit wasn't enforced. This was fixed in v4.2.1.

If you don't want any limit, you can set it to ```null```, ```0``` or ```Infinity```.

**Comment by Kamelia2000** [comment]
Because you understand better just refer to your whats app and look you want to implement this by Socketcluster.forst Socketcluster advise make channel and destroy them :

1- It means you never have all people  inside your chat room anytimes you need to access need to make channel and subscriber its huge of access

**Comment by jondubois** [comment]
In case of worker crash, the clients should not all reconnect at the exact same time. The SC JavaScript client has a random delay which can be configured. This randomness ensures that client reconnections are spread out over a certain period of time. Also, problems like this can simply be handled by adding more machines.

**Comment by Kamelia2000** [comment]
So whats your suggestion for Pub/Sub and Group chat in enterprise? Could you tell me how possible to connect Pub/sub inside this system and connect to cluster ? Because as i understand Socketcluster is not suitable for Pub/Sub

**Comment by jondubois** [comment]
@Kamelia2000 docs: https://socketcluster.io/#!/docs/full-stack

**Comment by Kamelia2000** [comment]
I would like to know whwther possible to use Socketcluster for Geolocation ? Kamelia
