### ISSUE TITLE
Using emit('subscribe', {}) does not send message

### ISSUE THREAD

**Issue by marchaos** [SocketCluster/socketcluster-client#58]
It seems that 'subscribe' is used internally, as any other string that I tried seems to work. Can we add a delimiter to the internal message so that 'subscribe' works?

**Comment by jondubois** [comment]
@marchaos You cannot use event names which are local events on the socket.

There are three types of events in SC:
- Emitted from the socket on the opposite end of the connection
- Local/reserved events (typically emitted by SC itself).
- Protocol events

Protocol events are sent over the wire and always start with a `'#'` prefix so that they don't interfere with other over-the-wire events.
Unfortunately, local events are different - They do not have any prefix - That was mostly an aesthetic decision initially and also because we wanted SC to be consistent with Socket.io but I agree it's less than ideal.

If you try to emit a local/reserved event on the socket, it will be emitted locally on the current socket and not reach the socket on the opposite end of the connection.

The list of local/reserved events is here:
https://github.com/SocketCluster/socketcluster-client/blob/31f13f492b818c5ab943560d3e36b3ec5b674fe4/lib/scsocket.js#L54-L71

So in the meantime, you should avoid emitting these events.

Version 6 of SC will break API compatibility so that would be a good opportunity to rethink this behavior and fix this issue. If we add a special prefix to the event name; we could have to do it for ALL local events (this will make all the event names quite long). One possible solution would be to to make it such that events which come from the opposite side of the socket could have their own event listener function (E.g. instead of using the `socket.on(eventName, handler)` we could have a separate `socket.listen(eventName, handler)` just for events which were emitted remotely)... Happy to hear suggestions.

**Comment by jondubois** [comment]
New versions of the client now emit an error event when you try to emit a reserved event name.
