### ISSUE TITLE
[Question] Which is the logic on tagging libraries?

### ISSUE THREAD

**Issue by thomasvargiu** [SocketCluster/socketcluster-client#95]
I saw that tags, releases and changelog are not updated on new versions, and I can't understand which is the logic on tagging.

For example, last version 9.0 just introduced a new event, but it doesn't seem a BC, so I think you are not following [semver](https://semver.org/), that makes difficult to stay updated with libraries.

Wich is the current logic?

**Comment by jondubois** [comment]
@thomasvargiu Thanks for reporting. Regarding the first issue, I fell behind on the tagging - It should be up to date now.

This repo follows semver with one additional rule:

If the SocketCluster framework (https://github.com/SocketCluster/socketcluster) is bumped up to a new major version, then the next version of the client (this repo) will also be bumped up to the matching major version (even if there are no breaking changes). This is to make it easier for users to figure out which client version is compatible with which server version.

There haven't been any breaking changes to this repo for a long time.
The SC protocol hasn't had a breaking change for years now. There was an extension to the SC protocol to support batching in `v8.x.x` but it's an optional feature so that was backwards compatible as well.

**Comment by thomasvargiu** [comment]
Now I understand. Thank you 👍
